{{ if .Values.endpoint }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: external-service
  labels:
    some: label
subsets:
- addresses:
  - ip: 10.10.10.10
  ports:
  - port: 8080
{{ end }}
{{ if .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  selector:
    some: label
  ports:
  - port: 80
    targetPort: 8080
{{ end }}
