apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  ports:
  - port: 80
    targetPort: 8080
---
kind: Endpoints
apiVersion: v1
metadata:
  name: external-service
subsets:
- addresses:
    ip: 10.10.10.10
  ports:
    port: 8080
